using System;
using MarcoERP.Domain.Entities.Common;

namespace MarcoERP.Domain.Entities.Sync
{
    /// <summary>
    /// Represents a registered sync client (mobile device, desktop, etc.).
    /// Tracks the last sync checkpoint per device so the server can send only deltas.
    /// </summary>
    public sealed class SyncDevice : AuditableEntity
    {
        private SyncDevice() { }

        public SyncDevice(string deviceId, string deviceName, string deviceType, int userId)
        {
            if (string.IsNullOrWhiteSpace(deviceId))
                throw new ArgumentException("Device ID is required.", nameof(deviceId));

            DeviceId = deviceId.Trim();
            DeviceName = deviceName?.Trim() ?? "Unknown";
            DeviceType = deviceType?.Trim() ?? "Mobile";
            UserId = userId;
            LastSyncVersion = 0;
            LastSyncAt = null;
            IsActive = true;
        }

        /// <summary>Unique device identifier (UUID generated by client).</summary>
        public string DeviceId { get; private set; }

        /// <summary>Human-readable device name.</summary>
        public string DeviceName { get; private set; }

        /// <summary>Device type: Mobile, Desktop, Tablet.</summary>
        public string DeviceType { get; private set; }

        /// <summary>The user who owns this device.</summary>
        public int UserId { get; private set; }

        /// <summary>Last SyncVersion successfully pulled by this device.</summary>
        public long LastSyncVersion { get; private set; }

        /// <summary>UTC timestamp of the last successful sync.</summary>
        public DateTime? LastSyncAt { get; private set; }

        /// <summary>Whether this device is active for sync.</summary>
        public bool IsActive { get; private set; }

        public void UpdateSyncCheckpoint(long syncVersion, DateTime syncedAt)
        {
            if (syncVersion < LastSyncVersion)
                return; // Never go backwards

            LastSyncVersion = syncVersion;
            LastSyncAt = syncedAt;
        }

        public void Deactivate() => IsActive = false;
        public void Activate() => IsActive = true;
    }
}
